"""
Central configuration for the NCAA volleyball capstone project.
"""

from pathlib import Path


############################
# Project directories
############################

PROJECT_ROOT = Path(__file__).resolve().parent.parent

DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
INTERIM_DATA_DIR = DATA_DIR / "interim"
PROCESSED_DATA_DIR = DATA_DIR / "processed"

OUTPUTS_DIR = PROJECT_ROOT / "outputs"
NOTEBOOKS_DIR = PROJECT_ROOT / "notebooks"
DOCS_DIR = PROJECT_ROOT / "docs"


############################
# Input and output files
############################

# The only manually maintained population file.
SCHOOL_LIST_FILE = RAW_DATA_DIR / "school_list.csv"

# Generated by discover_roster_urls.py.
ROSTER_SOURCES_FILE = INTERIM_DATA_DIR / "roster_sources.csv"

# Generated by collect_rosters.py.
ROSTERS_FILE = RAW_DATA_DIR / "rosters.csv"
COLLECTION_LOG_FILE = OUTPUTS_DIR / "collection_log.csv"


############################
# Study parameters
############################

START_YEAR = 2018
END_YEAR = 2025

SEASONS = list(
    range(
        START_YEAR,
        END_YEAR + 1,
    )
)


############################
# Web collection settings
############################

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 "
        "(Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 "
        "(KHTML, like Gecko) "
        "Chrome/150.0.0.0 Safari/537.36"
    )
}

REQUEST_TIMEOUT = 30
REQUEST_DELAY = 1.5